# Standard
CC = g++ 
CFLAGS = -std=c++11 -Wall -Wextra -fdiagnostics-color=always -O0

IDIR= ./
SRC= $(IDIR)modele2.cpp

# compile
all: $(SRC)
	$(CC) $(CFLAGS) $(SRC) -o modele2.o

# remove compilation products
clean:
	rm -f *.o
